name: 'File Changes Action'
description: 'Creates outputs variables of files modified, added, or deleted by a PR or Push.'
author: 'Bryan Killian <me@trilom.org>'
inputs:
  githubToken:
    description: 'The GITHUB_TOKEN secret if necessary'
    required: false
  output:
    description: 'Choose between json (default), or custom delimiter by passing a string, for example '','' for csv variable output'
    required: true
    default: json
  fileOutput:
    description: 'Choose between json (default), or custom delimiter by passing a string, for example '','' for csv file output.  If you set as json the file output will be suffixed with .json, if you select '','' then the output will be .csv, else .txt will be the output.'
    required: true
    default: json
outputs:
  files:
    description: 'The names all new, updated, and deleted files'
  files_added:
    description: 'The names of the newly created files'
  files_modified:
    description: 'The names of the updated files'
  files_deleted:
    description: 'The names of the deleted files'
runs:
  using: 'node12'
  main:  'dist/index.js'
branding:
  icon:  'file-text'
  color: 'red'
